# -*- coding: utf-8 -*-
"""code_02_animation_collatz3_voronoi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ADGYZ77_AuWNAOWofWdJE8e5uN3bg_F5
"""

# Copyright (c) 2026 Hiroshi Harada
# Licensed under the MIT License.
# https://opensource.org/licenses/MIT
# Author: Hiroshi Harada
# Date: April 25, 2026


import sys
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import Voronoi
from matplotlib.colors import LinearSegmentedColormap
import matplotlib.patheffects as patheffects
from matplotlib.animation import FuncAnimation, PillowWriter

# ------------------------------------------------------------
# 1. Coordinate Mapping (3-adic Logarithmic Spiral)
# ------------------------------------------------------------
def to_polar(n):
    """
    Maps a natural number n to (x, y) coordinates on a 3-adic logarithmic spiral.
    """
    if n <= 0:
        return 0, 0
    r = np.log(n) / np.log(3)
    theta = 2 * np.pi * (r % 1)
    return r * np.cos(theta), r * np.sin(theta)

# ------------------------------------------------------------
# 2. Trajectory Depth Analysis (Memoized)
# ------------------------------------------------------------
depth_cache = {1: 0}

def get_collatz3_depth(n):
    """
    Calculates the step count (depth) from n to 1 in Collatz-3 mapping.
    Utilizes memoization for high-performance recursive path tracking.
    """
    if n in depth_cache:
        return depth_cache[n]

    current = n
    depth = 0
    visited = []

    while current not in depth_cache:
        visited.append(current)
        c = current % 3
        if c == 2:
            c = -1  # Balanced ternary adjustment
        if c == 0:
            current = current // 3
        else:
            current = (4 * current - c) // 3
        depth += 1

        # Safety break to prevent infinite loops on divergent paths
        if depth > 50000:
            break

    base = depth_cache.get(current, 0)
    for i, v in enumerate(reversed(visited)):
        depth_cache[v] = base + i + 1

    return depth_cache[n]

# ------------------------------------------------------------
# 3. Animation Engine: Preimage Propagation
# ------------------------------------------------------------
def generate_collatz_video(max_points=3000, display_limit=1000, filename="collatz3_evolution.gif"):
    print("[*] Initializing 3-adic Collatz Animation Engine...")

    # --- A. Voronoi Mother Points Generation ---
    core_points = np.array([to_polar(i) for i in range(1, max_points + 1)])

    # Add dummy points at the outer boundary to close infinite Voronoi cells
    max_r = np.log(max_points) / np.log(3)
    theta_dummy = np.linspace(0, 2*np.pi, 64, endpoint=False)
    dummy = np.column_stack((max_r * 1.5 * np.cos(theta_dummy),
                             max_r * 1.5 * np.sin(theta_dummy)))

    points = np.vstack([core_points, dummy])
    vor = Voronoi(points)

    # --- B. Depth Mapping & CDF Normalization ---
    depth_map = {n: get_collatz3_depth(n) for n in range(1, display_limit + 1)}
    max_depth = max(depth_map.values())

    # Equalize color distribution using Cumulative Distribution Function (CDF)
    depth_values = list(depth_map.values())
    unique_depths, counts = np.unique(depth_values, return_counts=True)
    cdf = np.cumsum(counts) / len(depth_values)
    depth_to_percentile = dict(zip(unique_depths, cdf))

    # --- C. Plot Initialization ---
    fig, ax = plt.subplots(figsize=(14, 14), facecolor="black")
    ax.set_facecolor("black")

    # Custom Spectrum: Blue (Origin) -> Lime -> Yellow -> Orange -> Red (Deep)
    colors = ["#0022FF", "#00FF44", "#FFFF00", "#FF7700", "#FF0000"]
    cmap = LinearSegmentedColormap.from_list("collatz3_spectrum", colors, N=256)

    # --- D. Pre-rendering Tiles and Labels ---
    tiles = []
    labels = []

    for point_idx, region_idx in enumerate(vor.point_region):
        n = point_idx + 1
        if n > display_limit:
            continue

        region = vor.regions[region_idx]
        if -1 in region or len(region) == 0:
            continue

        # Sort polygon vertices by angle to prevent twisted geometry rendering
        polygon = np.array([vor.vertices[i] for i in region])
        center = polygon.mean(axis=0)
        angles = np.arctan2(polygon[:, 1] - center[1], polygon[:, 0] - center[0])
        polygon = polygon[np.argsort(angles)]

        depth = depth_map[n]
        percentile = depth_to_percentile.get(depth, 0.0)

        # Initialize hidden tiles (alpha=0.0)
        patch = plt.Polygon(
            polygon,
            facecolor=cmap(percentile),
            edgecolor="black",
            lw=0.3,
            alpha=0.0,
            zorder=2
        )
        ax.add_patch(patch)
        tiles.append((depth, patch))

    # Pre-render text labels
    for n in range(1, display_limit + 1):
        x, y = core_points[n - 1]
        depth = depth_map[n]

        # Style differentiation: Dim 3-multiples, highlight injectors/launchers
        is3 = (n % 3 == 0)
        target_alpha = 0.45 if is3 else 0.95
        weight = "normal" if is3 else "bold"
        size = 6 if is3 else 7.5

        # Initialize hidden text (alpha=0.0)
        txt = ax.text(
            x, y, str(n),
            fontsize=size,
            ha="center", va="center",
            color="white",
            alpha=0.0,
            fontweight=weight,
            zorder=5,
            path_effects=[patheffects.withStroke(linewidth=1.5, foreground="black")]
        )
        labels.append((depth, txt, target_alpha))

    # --- E. Axes and Layout Configuration ---
    r_limit = np.log(display_limit) / np.log(3)
    ax.set_xlim(-r_limit - 0.2, r_limit + 0.2)
    ax.set_ylim(-r_limit - 0.2, r_limit + 0.2)
    ax.set_aspect("equal")
    ax.axis("off")

    title = ax.set_title(
        "3-adic Collatz Stained Glass Evolution\nDepth: 0",
        color="white", fontsize=20, fontweight="bold", pad=30
    )

    plt.tight_layout()

    # --- F. Frame Normalization (Constant Duration) ---
    # Compress the timeline into exactly 300 frames, plus 10 hold frames at the end
    frame_steps = np.linspace(0, max_depth, 300, dtype=int)
    frames = list(frame_steps) + [max_depth] * 10

    # --- G. Animation Update Function ---
    def update(frame):
        title.set_text(f"3-adic Collatz Stained Glass Evolution\nDepth: {frame}")

        # Reveal tiles that are born at or before the current depth
        for d, patch in tiles:
            if patch.get_alpha() == 0.0 and d <= frame:
                patch.set_alpha(0.88)

        # Reveal text labels with a slight pre-fade effect
        for d, txt, target_alpha in labels:
            current_alpha = txt.get_alpha()
            if current_alpha < target_alpha and d <= frame:
                txt.set_alpha(target_alpha)
            elif current_alpha == 0.0 and d <= frame + 1:
                txt.set_alpha(target_alpha * 0.6)

        return []

    # --- H. Rendering and Export ---
    print(f"[*] Compiling {len(frames)} frames to {filename}...")

    # CLI Progress Bar Callback
    def print_progress(current_frame, total_frames):
        percent = 100 * current_frame / total_frames
        bar_length = 30
        filled_length = int(bar_length * current_frame // total_frames)
        bar = '=' * filled_length + '>' + '-' * (bar_length - filled_length - 1)
        sys.stdout.write(f"\r[*] Progress: [{bar}] {percent:.1f}% ({current_frame}/{total_frames})")
        sys.stdout.flush()

    ani = FuncAnimation(fig, update, frames=frames, blit=False)

    # Save using PillowWriter (no external dependencies required)
    ani.save(filename, writer=PillowWriter(fps=10), progress_callback=print_progress)

    print(f"\n[✓] Animation successfully saved: {filename}")
    plt.close()

# ------------------------------------------------------------
# Execute
# ------------------------------------------------------------
if __name__ == "__main__":
    generate_collatz_video(
        max_points=3500,
        display_limit=1000,
        filename="collatz3_stained_glass_n1000.gif"
    )