# -*- coding: utf-8 -*-
"""code_01_image_collatz3_voronoi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HaB-qYhV9DFXbBtraLofl1Yn4RbqHJvp
"""

# Copyright (c) 2026 Hiroshi Harada
# Licensed under the MIT License.
# https://opensource.org/licenses/MIT
# Author: Hiroshi Harada
# Date: April 25, 2026


import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import Voronoi
from matplotlib.colors import LinearSegmentedColormap
import matplotlib.patheffects as patheffects
import os

# -----------------------------------------------------------------------------
# 1. Coordinate Mapping (3-adic Logarithmic Spiral)
# -----------------------------------------------------------------------------
def to_polar(n):
    """
    Maps a natural number n to (x, y) coordinates on a 3-adic logarithmic spiral.
    r = log3(n), theta = 2 * PI * frac(log3(n))
    """
    if n <= 0:
        return 0, 0
    r = np.log(n) / np.log(3)
    theta = 2 * np.pi * (r % 1)
    return r * np.cos(theta), r * np.sin(theta)

# -----------------------------------------------------------------------------
# 2. Trajectory Depth Analysis (Memoized)
# -----------------------------------------------------------------------------
depth_cache = {1: 0}

def get_collatz3_depth(n):
    """
    Calculates the step count (depth) from n to 1 in Collatz-3 mapping.
    Includes memoization for high-performance recursive path tracking.
    """
    if n in depth_cache:
        return depth_cache[n]

    current = n
    depth = 0
    visited = []

    while current not in depth_cache:
        visited.append(current)
        c = current % 3
        if c == 2:
            c = -1  # Balanced ternary adjustment
        if c == 0:
            current = current // 3
        else:
            current = (4 * current - c) // 3
        depth += 1
        if depth > 20000:  # Safety break for divergent paths
            break

    base_depth = depth_cache.get(current, 0)
    for i, v in enumerate(reversed(visited)):
        depth_cache[v] = base_depth + i + 1

    return depth_cache[n]

# -----------------------------------------------------------------------------
# 3. Visualization Engine: Collatz Stained Glass
# -----------------------------------------------------------------------------
def generate_collatz_stained_glass(max_points=3000, display_limit=1000, save_png=True):
    """
    Generates a Voronoi-based 'Stained Glass' visualization for Collatz-3.
    """
    print(f"[*] Initializing Nadica Phase 2 Engine...")

    # --- A. Core Point Generation ---
    core_points = np.array([to_polar(i) for i in range(1, max_points + 1)])

    # --- B. Boundary Stabilization (Dummy points to close outer Voronoi cells) ---
    max_r = np.log(max_points) / np.log(3)
    theta_dummy = np.linspace(0, 2*np.pi, 64, endpoint=False)
    dummy_points = np.column_stack((max_r * 1.5 * np.cos(theta_dummy),
                                    max_r * 1.5 * np.sin(theta_dummy)))
    points = np.vstack([core_points, dummy_points])

    # Compute Voronoi Partition
    vor = Voronoi(points)

    # --- C. Depth Mapping & Histogram Equalization (CDF) ---
    depth_map = {n: get_collatz3_depth(n) for n in range(1, display_limit + 1)}
    depth_values = list(depth_map.values())
    unique_depths, counts = np.unique(depth_values, return_counts=True)
    cdf = np.cumsum(counts) / len(depth_values)
    depth_to_percentile = dict(zip(unique_depths, cdf))

    # --- D. Plot Setup ---
    fig, ax = plt.subplots(figsize=(16, 16), facecolor='black')
    ax.set_facecolor('black')

    # Custom Spectrum: Blue (Deep) -> Lime -> Yellow -> Orange -> Red (Edge)
    colors = ["#0022FF", "#00FF44", "#FFFF00", "#FF7700", "#FF0000"]
    custom_cmap = LinearSegmentedColormap.from_list("nadica_spectrum", colors, N=256)

    # --- E. Render Voronoi Tiles ---
    print(f"[*] Rendering {display_limit} topological tiles...")
    for point_idx, region_idx in enumerate(vor.point_region):
        n = point_idx + 1
        if n > display_limit:
            continue

        region = vor.regions[region_idx]
        if -1 in region or len(region) == 0:
            continue

        polygon = [vor.vertices[i] for i in region]
        percentile = depth_to_percentile.get(depth_map[n], 0.0)

        ax.fill(*zip(*polygon),
                color=custom_cmap(percentile),
                edgecolor='black',
                lw=0.3,
                alpha=0.85)

    # --- F. Numerical Labeling ---
    print(f"[*] Applying numerical labels with path-effects...")
    for n in range(1, display_limit + 1):
        x, y = core_points[n-1]

        # Style logic: Dim 3-multiples (Cooling), Highlight non-multiples (Injectors)
        is_3_multiple = (n % 3 == 0)
        alpha = 0.45 if is_3_multiple else 0.95
        weight = "normal" if is_3_multiple else "bold"
        size = 6 if is_3_multiple else 7.5

        ax.text(
            x, y, str(n),
            fontsize=size,
            ha='center', va='center',
            color='white',
            alpha=alpha,
            fontweight=weight,
            zorder=5,
            path_effects=[patheffects.withStroke(linewidth=1.5, foreground='black')]
        )

    # --- G. Final Touches ---
    r_limit = np.log(display_limit) / np.log(3)
    ax.set_xlim(-r_limit - 0.2, r_limit + 0.2)
    ax.set_ylim(-r_limit - 0.2, r_limit + 0.2)
    ax.set_aspect('equal')
    ax.axis('off')

    title = f"3-adic Collatz Stained Glass (Voronoi Topology)\nRange: 1 to {display_limit}"
    plt.title(title, color='white', fontsize=20, fontweight='bold', pad=30)
    plt.tight_layout()

    # --- H. Save and Show ---
    if save_png:
        filename = f"collatz3_stained_glass_n{display_limit}.png"
        print(f"[*] Exporting high-resolution image: {filename}")
        plt.savefig(filename, facecolor='black', dpi=300, bbox_inches='tight')

    print(f"[*] Visualization complete.")
    plt.show()

if __name__ == "__main__":
    generate_collatz_stained_glass(max_points=3500, display_limit=1000)

